language: php
php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2


before_install:
    - composer self-update


before_script:
    # Install Nette Tester & Code Checker
    - travis_retry composer install --no-interaction --prefer-source
    - travis_retry composer create-project nette/code-checker code-checker ~2.2 --no-interaction --prefer-source


script:
    - php code-checker/src/code-checker.php -d libs
    - vendor/bin/phpunit


notifications:
    email: false


cache:
    directories:
        - $HOME/.composer/cache
